SoccerAcademy:
    trainer: ppo # Comment
    beta: 5.0e-3
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 128
    num_epoch: 3
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    normalize: false
    max_steps: 5.0e7
    learning_rate_schedule: constant
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 512
    time_horizon: 1000
    num_layers: 2
    self_play:
        window: 10
        play_against_latest_model_ratio: 0.5
        save_steps: 50000
        swap_steps: 50000
        team_change: 200000