# Behaviour Name
SoccerAcademy:

    # Common Trainer Configurations
    trainer: ppo
    summary_freq: 10000
    batch_size: 5120
    buffer_size: 512000
    hidden_units: 512
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 100000000
    normalize: false
    num_layers: 3
    time_horizon: 1024

    # PPO-specific hyperparameters
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3

    # Reward Signals
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

    # Memory-enhanced Agents
    use_recurrent: false
    memory_size: 128
    sequence_length: 128