# Behaviour Name
SoccerAcademy:

    # Common Trainer Configurations
    trainer: ppo
    summary_freq: 100000
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 512
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 10000000
    normalize: false
    num_layers: 2
    time_horizon: 1024

    # PPO-specific Configurations
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3

    # Reward Signals
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

    # Memory-enhanced Agents
    use_recurrent: true
    memory_size: 128
    sequence_length: 64