# Behaviour Name
SoccerAcademy:

  # Curricula B
  measure: progress
  min_lesson_length: 100
  signal_smoothing: true
  thresholds: [0.1, 0.2, 0.3]
  parameters:
    ball_touch_reward: [0.3, 0.2, 0.1, 0.0]