# Curricula C
SoccerAcademy:
  measure: progress
  min_lesson_length: 100
  signal_smoothing: true
  thresholds: [0.1, 0.2, 0.3, 0.4, 0.5]
  parameters:
    opponent_speed: [0.0, 0.0, 0.5, 1.0, 1.5, 2.0]
    opponent_exist: [0.0, 1.0, 1.0, 1.0, 1.0, 1.0]